/**
 * BUBEO STORE - PRODUCT DATA
 * 
 * This file contains all product information including:
 * - Product details (ID, name, category, price, description)
 * - Available sizes and colors for each product
 * - Product assets/images and badges
 * - Size and color reference maps
 * 
 * To add or modify products, edit the 'products' array below.
 */

// Color palette used across all products
const commonColors = [
  { name: "Hồng", value: "#ff9aca" },
  { name: "Trắng", value: "#ffffff" },
  { name: "Đen", value: "#2f2a2d" },
  { name: "Be", value: "#e8d5be" },
  { name: "Xanh", value: "#a9d8ff" },
  { name: "Xám", value: "#A8AAA6" },
  { name: "Green", value: "#1A2421" },
  { name: "Orange", value: "#FF7E00" }


];

// Convert color array to object for quick lookup
const colorMap = Object.fromEntries(commonColors.map(color => [color.name, color.value]));

// Standard sizes available across products
const commonSizes = ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"];

// All products in the catalog
const products = [
  {
    id: 1,
    name: "Classic Màu Be",
    category: "classic",
    badge: "Bán chạy",
    price: "240k",
    description: "Dép sục màu be nhẹ nhàng, dễ phối đồ và siêu đáng yêu.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Hồng", "Trắng", "Be", "Xanh", "Xám"],
    images: ["assets/images/classic_be/be1.png", "assets/images/classic_be/be2.JPG", "assets/images/classic_be/be3.JPG"],
  },
  {
    id: 2,
    name: "Classic Màu Xám",
    category: "classic",
    badge: "Bán chạy",
    price: "240k",
    description: "Dép sục màu xám cá tính, sạch màu và mang rất êm chân.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Hồng", "Trắng", "Be", "Xanh", "Xám"],
    images: ["assets/images/classic_xam_atmosphere/xam1.png", "assets/images/classic_xam_atmosphere/xam2.png", "assets/images/classic_xam_atmosphere/xam3.png", "assets/images/classic_xam_atmosphere/xam4.JPG"],
  },
  {
    id: 3,
    name: "Classic Màu Trắng",
    category: "classic",
    badge: "Bán chạy",
    price: "240k",
    description: "Dép sục màu trắng basic, xinh xắn và phù hợp nhiều phong cách.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Hồng", "Trắng", "Be", "Xanh", "Xám"],
    images: ["assets/images/classic_trang/trang1.heif", "assets/images/classic_trang/trang2.heif", "assets/images/classic_trang/trang3.png"],
  },
  {
    id: 4,
    name: "Classic Màu Hồng",
    category: "classic",
    badge: "Bán chạy",
    price: "240k",
    description: "Dép sục màu hồng ngọt ngào, nổi bật và siêu dễ thương.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Hồng", "Trắng", "Be", "Xanh", "Xám"],
    images: ["assets/images/classic_hong/hong1.JPG", "assets/images/classic_hong/hong2.JPG", "assets/images/classic_hong/hong3.JPG"],
  },
  {
    id: 5,
    name: "Baya Loang Đào Sữa",
    category: "classic",
    badge: "Bán chạy",
    price: "300k",
    description: "Mẫu loang đào sữa pastel nhẹ nhàng, xinh xắn cho outfit hằng ngày.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Hồng", "Xanh"],
    images: ["assets/images/baya_loang_dao_sua/dao1.heic", "assets/images/baya_loang_dao_sua/dao2.heic"],
  },
  {
    id: 6,
    name: "Baya Loang Xanh",
    category: "classic",
    badge: "Bán chạy",
    price: "300k",
    description: "Mẫu loang xanh pastel mát mắt, dễ thương và thoải mái khi mang.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Hồng", "Xanh"],
    images: ["assets/images/baya_loang_xanh/xanh1.heic", "assets/images/baya_loang_xanh/xanh2.JPG", "assets/images/baya_loang_xanh/xanh3.JPG"],
  },
  {
    id: 7,
    name: "Zootopia",
    category: "collab",
    badge: "Bán chạy",
    price: "500k",
    description: "Mẫu Zootopia vui nhộn, nổi bật với chi tiết đáng yêu.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Xanh"],
    images: ["assets/images/zootopia/zoo1.png", "assets/images/zootopia/zoo2.png", "assets/images/zootopia/zoo3.JPG", "assets/images/zootopia/zoo4.png", "assets/images/zootopia/zoo5.png"],
  },
  {
    id: 8,
    name: "Batman",
    category: "collab",
    badge: "Bán chạy",
    price: "400k",
    description: "Mẫu Batman màu đen cá tính, dễ phối và cực chất.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Đen"],
    images: ["assets/images/batman/batman1.JPG", "assets/images/batman/batman2.JPG", "assets/images/batman/batman3.JPG"],
  },
  {
    id: 9,
    name: "Hello Kitty",
    category: "collab",
    badge: "Bán chạy",
    price: "350k",
    description: "Mẫu Hello Kitty trắng hồng ngọt ngào, dành cho team mê phong cách cute.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Trắng"],
    images: ["assets/images/hello_kitty/kitty1.JPG", "assets/images/hello_kitty/kitty2.JPG"],
  },
  {
    id: 10,
    name: "Powerpuff Girls Blossom",
    category: "collab",
    badge: "Bán chạy",
    price: "400k",
    description: "Mẫu Powerpuff Girls Blossom màu hồng nổi bật, xinh và cá tính.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Hồng"],
    images: ["assets/images/powerpuff_girls_blossom/power.heic", "assets/images/powerpuff_girls_blossom/power.JPG"],
  },
  {
    id: 11,
    name: "Enamel Buckle Xanh Pastel",
    category: "collab",
    badge: "Hàng mới",
    price: "350k",
    description: "Mẫu Enamel Buckle xanh pastel nhẹ nhàng, có điểm nhấn khóa xinh xắn.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Xanh"],
    images: ["assets/images/buckle_xanh_pastel/buckle1.JPG", "assets/images/buckle_xanh_pastel/buckle2.JPG", "assets/images/buckle_xanh_pastel/buckle3.JPG"],
  },
  {
    id: 12,
    name: "Loopy",
    category: "collab",
    badge: "Hàng mới",
    price: "350k",
    description: "Mẫu Loopy màu hồng dễ thương, hợp phong cách trẻ trung.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Hồng"],
    images: ["assets/images/loopy/loopy.heic", "assets/images/loopy/loopy2.JPG", "assets/images/loopy/loopy3.JPG"],
  },
  {
    id: 13,
    name: "Hello Kitty Da Beo",
    category: "collab",
    badge: "Hàng mới",
    price: "250k",
    description: "Mẫu Hello Kitty da beo độc đáo, vừa cute vừa nổi bật.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Hồng", "Xanh"],
    images: ["assets/images/hello_kitty_da_beo/beo1.png", "assets/images/hello_kitty_da_beo/beo2.png", "assets/images/hello_kitty_da_beo/beo3.png", "assets/images/hello_kitty_da_beo/beo4.png", "assets/images/hello_kitty_da_beo/beo5.png"],
  },
  {
    id: 14,
    name: "Donut",
    category: "collab",
    badge: "Hàng mới",
    price: "500k",
    description: "Mẫu Donut ngọt ngào, màu sắc tươi tắn và cực kỳ đáng yêu.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Orange"],
    images: ["assets/images/donut/donut1.JPG", "assets/images/donut/donut2.JPG", "assets/images/donut/donut3.JPG"],
  },
  {
    id: 15,
    name: "Lotso",
    category: "collab",
    badge: "Hàng mới",
    price: "350k",
    description: "Mẫu Lotso màu hồng ngọt, mềm mại và dễ thương.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Hồng"],
    images: ["assets/images/classic_lotso/lotso1.JPG", "assets/images/classic_lotso/lotso2.JPG", "assets/images/classic_lotso/lotso3.JPG"],
  },
  {
    id: 16,
    name: "Ballet Đế Mềm",
    category: "classic",
    badge: "Hàng mới",
    price: "250k",
    description: "Mẫu Ballet nữ tính, dáng gọn nhẹ và dễ mang mỗi ngày.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Hồng", "Đen", "Trắng", "Be"],
    images: ["assets/images/crocs_ballet/ballet1.JPG", "assets/images/crocs_ballet/ballet2.png", "assets/images/crocs_ballet/ballet3.png", "assets/images/crocs_ballet/ballet4.png", "assets/images/crocs_ballet/ballet5.png"],
  },
  {
    id: 17,
    name: "Line Friends",
    category: "collab",
    badge: "Hàng mới",
    price: "350k",
    description: "Mẫu Line Friends đáng yêu, tông trắng dễ phối và trẻ trung.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Trắng"],
    images: ["assets/images/line_friends/line1.JPG", "assets/images/line_friends/line2.JPG", "assets/images/line_friends/line3.JPG"],
  },
  {
    id: 18,
    name: "Squishmallow",
    category: "collab",
    badge: "Hàng mới",
    price: "400k",
    description: "Mẫu Squishmallow mềm mại, cute và hợp phong cách năng động.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Trắng"],
    images: ["assets/images/squishmallow/mallow1.JPG", "assets/images/squishmallow/mallow2.JPG", "assets/images/squishmallow/mallow3.JPG", "assets/images/squishmallow/mallow4.JPG"],
  },
  {
    id: 19,
    name: "Snoopy Phiên Bản 2",
    category: "collab",
    badge: "Hàng mới",
    price: "350k",
    description: "Mẫu Snoopy phiên bản 2 tông trắng dễ thương, đơn giản mà nổi bật.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Trắng"],
    images: ["assets/images/snoopy_ver2/snoopy_ver2_1.JPG", "assets/images/snoopy_ver2/snoopy_ver2_2.JPG"],
  },
  {
    id: 20,
    name: "Minecraft",
    category: "collab",
    badge: "Hàng mới",
    price: "400k",
    description: "Mẫu Minecraft màu xanh cá tính, vui nhộn và khác biệt.",
    sizes: ["36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43"],
    colors: ["Green"],
    images: ["assets/images/minecraft/mc1.JPG", "assets/images/minecraft/mc2.JPG", "assets/images/minecraft/mc3.JPG"],
  },
];
